### ISSUE TITLE
yakyak doesn't work on chromium & ff

### ISSUE THREAD

**Issue by sbisbee** [rwaldron/jquery.eventsource#1]
Browser: chromium
Version: 6.0.472.62 (59676) Ubuntu 10.04

Browser: Firefox
Version: 3.6.10 (Ubuntu 10.04)

The chat area was one big blank, white area. Don't know if people saw what I sent to the channel.

**Comment by rwaldron** [comment]
Will address when conf is over - thanks Sam.
