### ISSUE TITLE
issue :: streamData[idx].split is not a function

### ISSUE THREAD

**Issue by dobrys** [rwaldron/jquery.eventsource#4]
seems to have issue with master branch file jquery.eventsource.js 
when using Example 3 : JSON open callback (url: '../test-event-sources/event-source-2.php')

there are JS error : "streamData[idx].split is not a function"
seems error caused by line: 125:
" return !!sdata && sdata;"
when I changed it with code from "futures" branch

if ( sdata ) {
       return sdata;
 }

issue disapear

This happens on Windows7 professional Apache Web Server , browser FireFox 4.0.1

**Comment by rwaldron** [comment]
Patched! The changes are in the master branch now - Thanks for filing the ticket!
